### ISSUE TITLE
Not working with npm 2.14.12

### ISSUE THREAD

**Issue by grahamb** [ryanflorence/react-project#15]
I'm trying to use react-project with node v4.3.1 (the current LTS version), which ships with npm v2.14.2. Running `npm start` crashes with an error. I've pasted a full output from the initial `npm install react-project` up to the crash in `npm start` at https://gist.github.com/grahamb/3a3ae1afe6312d648ed3

Using either node v5 (npm v3.6.0) , or upgrading npm under node v4.3.1 to the latest (v3.7.5) works.

**Comment by luandro** [comment]
Should add a note to README, I had the same problem.

**Comment by ryanflorence** [comment]
added a note in the readme, thanks.
