### ISSUE TITLE
eslint not being installed

### ISSUE THREAD

**Issue by ryanflorence** [ryanflorence/react-project#19]
I made a few updates last night but for whatever reason, things are broken so I had to put the latest dist-tag back to 0.0.4.

The problem is that all the scripts that npm normally installs to `node_modules/.bin` aren't getting there.

``` sh
mkdir test
cd test
npm init
npm install react-project@0.0.7
node_modules/.bin/react-project init
npm install
ls node_modules/.bin
# no eslint (among others)
ls node_modules
# eslint was installed though :\
```

And of course:

```
rm -rf node_modules
npm install
```

It works.

Do all of that but do `npm install react-project@0.0.6` and it installs eslint.

Here's the compare, makes no sense at all: https://github.com/ryanflorence/react-project/compare/v0.0.6...v0.0.7

**Comment by bdsabian** [comment]
@ryanflorence Looks like you changed 

`const blueprintPkg = require('../blueprint/package.json')`
to
`const blueprintPkg = require('../blueprint_package.json')`

on line 26 of modules/start.js, but there is no blueprint_package.json.  Seems like that should not have changed?

**Comment by ryanflorence** [comment]
yeah, that's on purpose:

https://github.com/ryanflorence/react-project/blob/master/scripts/release.sh#L47
https://github.com/ryanflorence/react-project/blob/master/scripts/mv-stuff.js

don't want the cp -R of blueprint (https://github.com/ryanflorence/react-project/blob/master/modules/init.js#L20-L23) to override the existing package.json in the app

but it's the only thing that changed ... its' so weird that `eslint` (and others) gets installed, but the bin scripts aren't symlinked ...

**Comment by ryanflorence** [comment]
went back to just having `package.json` live in the blueprint, not sure why some folks report their local one being overwritten, doesn't happen for me, I have a new idea for the blueprint anyway.
