### ISSUE TITLE
Images in legacy CSS not resolved

### ISSUE THREAD

**Issue by tomhallam** [ryanflorence/react-project#28]
Hey,

Just getting started with this library, really like it - thought I'd try and use Semantic UI CSS for my example app - have imported as follows (after having set up and verified the .css file exists):

**routes.js**
`import '../semantic/dist/semantic.css'`

When attempting to compile I get the following:

```
ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./semantic/dist/semantic.css
Module not found: Error: Cannot resolve module 'themes/default/assets/images/flags.png' in <project dir>/semantic/dist
 @ ./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./semantic/dist/semantic.css 6:206749-206798
```

As well as PNG files it seems to fall over with .eot, .woff2, .woff, ttf and SVG. 

I've looked in the various configuration files and it looks like it should be covered in the regexes. 

Can you help? Apologies for the newbie question.

**Comment by ryanflorence** [comment]
where is semantic coming from? npm install '...' or just downloaded the files?

**Comment by tomhallam** [comment]
Hey,

I npm installed, when you do this it creates a directory at the root level, when you do a `gulp build` it compiles to minified CSS, which is where the `../semantic/dist/semantic.css` comes from.

Tom

**Comment by ryanflorence** [comment]
images and stuff are working fine for me, if you can provide a test case somewhere I'll take a look, until then I'm closing.

This project is really early, help is welcome, but I'm not going to be spending time chasing down other people's issues right now, first I'm fixing the ones I'm running into myself. If you want this fixed, please fix it :)
