### ISSUE TITLE
init doesn't work on Windows (dependency issue)

### ISSUE THREAD

**Issue by insin** [ryanflorence/react-project#3]
react-project@0.0.3 on Windows 7 Enterprise 64-bit

```
> node -v
v4.2.6
> npm -v
2.14.12
```

```
> node_modules\.bin\react-project init
[react-project] [init] task
[react-project] This is going to add a bunch of files and edit your package.json
. You probably want to have a clean git working tree before continuing. That way
 you can reset the changes about to made with `git reset`.
[react-project] Do you want to continue? (y/N)
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\dev\stdin'
```

It looks like `prompt-sync` has Windows support, but not in the version published to npm - see 0x00A/prompt-sync#10.

**Comment by heapwolf** [comment]
@insin published `+ prompt-sync@3.0.1`

**Comment by insin** [comment]
Awesome, thanks!

Confirming that `init` works when I monkey-install `prompt-sync@3.0.1` into react-project's deps.

**Comment by mattdufeu** [comment]
Actually, the PR just removes the error above, it still doesn't work. I had to remove the following line from node_modules\react-project\lib\init.js:

(0, _LogUtils.promptApproval)('Do you want to continue?');

I'm out of my depth now

**Comment by heapwolf** [comment]
I don't have a windows VM at the moment, but please let me know if i can be of further assistance.
:beers:

**Comment by ryanflorence** [comment]
since @0x00A and @insin both seem to think it should be working w/ the new version I'm closing this issue, if it's still a problem I'm sure another issue will be opened. Thanks :)
