### ISSUE TITLE
 Octal literal in strict mode

### ISSUE THREAD

**Issue by farzd** [ryanflorence/react-project#4]
![image](https://cloud.githubusercontent.com/assets/1423413/13284695/d10fb780-daed-11e5-8e45-ec7c54618b10.png)

**Comment by jaredpalmer** [comment]
+1

Just tried to follow the install instructions. Got the same error. 

This project is brilliant btw, @ryanflorence keeping it :100:

**Comment by chriscorwin** [comment]
Also getting this.

Will keep poking!

**Comment by ryanflorence** [comment]
Opened the issue with prompt-sync, I think we should probably switch to https://www.npmjs.com/package/prompt since its seen a lot more usage.

**Comment by ryanflorence** [comment]
switched to `prompt`, should probably be fine now.
