### ISSUE TITLE
Missing .gitignore/.npmrc when running init

### ISSUE THREAD

**Issue by latentflip** [ryanflorence/react-project#8]
Just installed, and when running init I get the following output with react-project 0.0.4

```
[react-project] [init] task
[react-project] This is going to add a bunch of files and edit your package.json. You probably want to have a clean git working tree before continuing. That way you can reset the changes about to made with `git reset`.
prompt: Do you want to continue? (y|n):  (n) y
[react-project] copying project blueprint
cp: no such file or directory: /Users/latentflip/fo/node_modules/react-project/blueprint/.gitignore
cp: no such file or directory: /Users/latentflip/fo/node_modules/react-project/blueprint/.npmrc
[react-project] Adding scripts to package.json
[react-project]
[react-project] Now run:
[react-project]
[react-project]   npm install && npm start
[react-project]
[react-project] [init] task complete
```

I'm guessing it's npm being extra greedy about which files to omit when publishing? Perhaps it needs to be overridden somehow to explicitly push those to npm? Or rename the files without a `.` and rename on copy?

**Comment by ryanflorence** [comment]
Oh yep, probably can add to "files" key in package.json

**Comment by ryanflorence** [comment]
npm publish removes them ...

**Comment by phated** [comment]
@ryanflorence yeah, for security (npmrc), I think this is the reason yeoman always suggested naming dotfile without the dot and copying them to a filename with the dot added.

**Comment by ryanflorence** [comment]
I've got a fix coming
