### ISSUE TITLE
`react-project init` removes `react-project` from package.json dependencies list when running init

### ISSUE THREAD

**Issue by latentflip** [ryanflorence/react-project#9]
Not sure if this is intentional or not? But after running through the setup instructions, `react-project` has been removed from package.json -- looks like because the deps are replaced not merged, and react-project isn't in the boilerplate package.json.

**Comment by ryanflorence** [comment]
Ha, woops, it should stay there. Probably busted that when renaming stuff

**Comment by ryanflorence** [comment]
It's because package.json is completely replaced I think
